### ISSUE TITLE
Scatter Login // Update your EOS Account

### ISSUE THREAD

**Issue by solomon18** [boid-com/webboid#22]
As a new user to boid and EOS, I've been struggling to connect the EOS account.

Attached are some error messages that I get from Firefox and Chrome running on macOS.

![Screen Shot 2021-04-17 at 9 34 26 PM](https://user-images.githubusercontent.com/4066364/115134421-c86e2480-9fc4-11eb-9cd0-d50340f4feec.png)

**Comment by jdheeter** [comment]
Have you tried restarting Scatter? Do you have a local firewall that might be blocking Scatter? Can you login with Scatter at bloks.io?

**Comment by solomon18** [comment]
Thank you for the help; I got it working. I was able to log in with Scatter at bloks.io. It seems that you would need to launch the Scatter from your local machine first, then try to link it via boid.

**Comment by jdheeter** [comment]
Great, we probably should specify that for new users.
